// File generated by FlutterFire CLI.
// ignore_for_file: type=lint

import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:firebase_core/firebase_core.dart' as firebase_core;
import 'firebase_options.dart';


/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart


// ...


/// ```
class DefaultFirebaseOptions {
  static firebase_core.FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const firebase_core.FirebaseOptions android = firebase_core.FirebaseOptions(
    apiKey: 'AIzaSyCXq09gnSdD3ZY7got2gZ-68prff0L9baA',
    appId: '1:298884771488:android:389328746d1649806923c5',
    messagingSenderId: '298884771488',
    projectId: 'limo-11f40',
    storageBucket: 'limo-11f40.firebasestorage.app',
  );

  static const firebase_core.FirebaseOptions ios = firebase_core.FirebaseOptions(
    apiKey: 'AIzaSyBzdf1T2wxPpbojn5JpSNeQZDhPEIw0XOA',
    appId: '1:298884771488:ios:89f477beacc422f96923c5',
    messagingSenderId: '298884771488',
    projectId: 'limo-11f40',
    storageBucket: 'limo-11f40.firebasestorage.app',
    iosBundleId: 'com.example.limo',
  );
}
